# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 个人简介
    url: /
    weight: 10
  - name: 论文成果
    url: /#papers
    weight: 11
  - name: 学术报告
    url: /#talks
    weight: 12
  - name: 最新动态
    url: /#news
    weight: 13
  - name: 工作经历
    url: experience/
    weight: 20
  - name: 项目展示
    url: projects/
    weight: 30
  - name: 课程资源
    url: courses/
    weight: 40
